imports:
    - { resource: config.yml }

parameters:
    database_name: vpn_prod
    database_user: vpn_user
    database_password: getmerich88!
    #PHP mail
    mailer_transport: sendmail
    mailer_host: 127.0.0.1
    mailer_user: ~
    mailer_password: ~

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
