#jms_security_extra:
#    secure_all_services: false
#    expressions: true

security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Mapes\UserBundle\Entity\Member: 
           algorithm: md5
           iterations: 1
           encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_SONATA_ADMIN]

    providers:
        #in_memory:
        #    memory:
        #        users:
        #            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
             entity: { class: Mapes\UserBundle\Entity\Member  }
             
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            #pattern:    ^/demo/secured/
            #form_login:
            #    check_path: /demo/secured/login_check
            #    login_path: /demo/secured/login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /user/login
                check_path:  /user/login_check
                always_use_default_target_path: true
                default_target_path: /user/loggedin
            logout:
                path:   /user/logout
                target: /user/login
                
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/user/secured, roles: ROLE_USER }
        #- { path: ^/_internal/bundles/redpcms/js/ckeditor/plugins/pdw/pdw_file_browser, roles: ROLE_ADMIN }
        
